services:
  postgres:
    image: 'bitnami/postgresql:17.2.0'
    networks:
       - app-tier
    environment:
      - 'POSTGRESQL_DATABASE=springhibernatetask'
      - 'POSTGRESQL_PASSWORD=${USER_PASSWORD}'
      - 'POSTGRESQL_USERNAME=${USER_NAME}'
      - 'POSTGRESQL_POSTGRES_PASSWORD=${USER_PASSWORD}'
    ports:
      - '15432:5432'
    volumes:
      - 'D:\postgresql:/bitnami/postgresql'
